# Generated by Django 4.2.5 on 2023-11-16 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='user', verbose_name='Profile')),
                ('address', models.TextField(blank=True, default='', verbose_name='Kullanıcı Adresi')),
                ('group', models.CharField(choices=[('yetkili', 'yetkili'), ('satici', 'satici'), ('normal', 'normal')], default='normal', max_length=50, verbose_name='Kullanıcı Sınıfı')),
                ('emailactive', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
